version: '3'

services:
  keycloak:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      DEBUG: true
      DEBUG_PORT: "*:8000"